//! Autogenerated JSON Schemas for the CLI's stable JSON outputs, plus a
//! markdown field-table rendering of each. The generated files are committed
//! under `docs/reference/schemas/` and embedded into the docs via pymdownx
//! snippets (`--8<--`), so the published reference is always exactly the Rust
//! types. A golden test ([`tests::generated_schemas_match_committed`]) fails if
//! a type drifts from its committed schema; regenerate with
//! `RSTEST_BLESS_SCHEMAS=1 cargo test -p rstest-cli schema`.
//!
//! Test-only: schemas are a documentation artifact, never emitted at runtime.
//! Adding an output is one entry in [`outputs`]; the `JsonSchema` derive on the
//! type does the rest.

use std::collections::HashMap;

use schemars::schema::{InstanceType, RootSchema, Schema, SchemaObject, SingleOrVec};
use schemars::schema_for;

/// Directory (repo-relative) the committed schema artifacts live in.
const OUT_DIR: &str = "docs/reference/schemas";

/// One documented JSON output: a stable `name` (the artifact filename stem), a
/// human `title`, the `source` that emits it, and its JSON Schema.
struct Output {
    name: &'static str,
    title: &'static str,
    source: &'static str,
    schema: RootSchema,
}

/// The outputs whose schema is published. Every stable JSON surface the CLI
/// emits is a typed serde struct; adding one here is all it takes.
fn outputs() -> Vec<Output> {
    vec![
        Output {
            name: "report-json",
            title: "Run report",
            source: "`--report-json`",
            schema: schema_for!(crate::reporting::report::Snapshot<'static>),
        },
        Output {
            name: "doctor-report",
            title: "Doctor report",
            source: "`--doctor-json`",
            schema: schema_for!(crate::doctor::DoctorReport),
        },
        Output {
            name: "discovery",
            title: "Discovery",
            source: "`--collect-only --report-json`",
            schema: schema_for!(crate::run::discovery::DiscoveryDoc),
        },
        Output {
            name: "migrate-check",
            title: "Migrate-check",
            source: "`migrate-check --migrate-check-json`",
            schema: schema_for!(crate::migrate::check::MigrateCheckDoc),
        },
        Output {
            name: "flake-log",
            title: "Flake log",
            source: "`.rstest_cache/flakes.json`",
            schema: schema_for!(HashMap<String, crate::reporting::flakes::FlakeStats>),
        },
    ]
}

/// A generated file: repo-relative path + full contents (trailing newline).
pub struct GeneratedFile {
    pub rel_path: String,
    pub contents: String,
}

/// Every artifact that should exist on disk: one `.schema.json` and one `.md`
/// field-table per output.
pub fn generated_files() -> Vec<GeneratedFile> {
    let mut files = Vec::new();
    for o in outputs() {
        let mut json = serde_json::to_string_pretty(&o.schema).expect("schema serializes");
        json.push('\n');
        files.push(GeneratedFile {
            rel_path: format!("{OUT_DIR}/{}.schema.json", o.name),
            contents: json,
        });
        files.push(GeneratedFile {
            rel_path: format!("{OUT_DIR}/{}.md", o.name),
            contents: render_md(&o),
        });
    }
    files
}

/// The generated markdown for one output: the root object, then a table per
/// referenced sub-type (definitions), in a stable (alphabetical) order.
fn render_md(o: &Output) -> String {
    let mut s = String::new();
    s.push_str(
        "<!-- Generated from the Rust type by `cargo test -p rstest-cli schema`. \
         Do not edit by hand; regenerate with RSTEST_BLESS_SCHEMAS=1. -->\n\n",
    );
    // Root type at `##`, its referenced sub-types at `###`, for clean toc nesting.
    render_object(&mut s, "##", o.title, o.source, &o.schema.schema);
    for (name, sch) in &o.schema.definitions {
        if let Schema::Object(obj) = sch {
            render_object(&mut s, "###", name, "", obj);
        }
    }
    // Exactly one trailing newline, matching pre-commit's end-of-file-fixer.
    let trimmed = s.trim_end().len();
    s.truncate(trimmed);
    s.push('\n');
    s
}

/// Render one object schema as a `heading` (markdown level marker) + optional
/// description + a property table. Also handles a map root (no properties, just
/// `additionalProperties`), which is how `flakes.json` is shaped.
fn render_object(s: &mut String, level: &str, heading: &str, source: &str, obj: &SchemaObject) {
    use std::fmt::Write;

    let _ = write!(s, "{level} {heading}\n\n");
    if !source.is_empty() {
        let _ = write!(s, "Source: {source}\n\n");
    }
    if let Some(desc) = description(obj) {
        let _ = write!(s, "{desc}\n\n");
    }

    let Some(ov) = &obj.object else {
        s.push('\n');
        return;
    };

    // A map type (e.g. nodeid -> record): no fixed properties, one value shape.
    if ov.properties.is_empty() {
        if let Some(ap) = &ov.additional_properties {
            let _ = write!(
                s,
                "An object mapping each key to a {} value.\n\n",
                type_label(ap)
            );
        }
        return;
    }

    s.push_str("| Field | Type | Required | Description |\n|---|---|---|---|\n");
    // `properties` is a BTreeMap, so iteration is already alphabetical & stable.
    for (field, sch) in &ov.properties {
        let required = if ov.required.contains(field) {
            "yes"
        } else {
            "no"
        };
        let ty = type_label(sch);
        let desc = match sch {
            Schema::Object(o) => description(o).unwrap_or_default(),
            Schema::Bool(_) => String::new(),
        };
        let _ = writeln!(s, "| `{field}` | {ty} | {required} | {desc} |");
    }
    s.push('\n');
}

/// A cell-safe one-line description from a schema's metadata (newlines folded,
/// `|` escaped so it can't break the table).
fn description(obj: &SchemaObject) -> Option<String> {
    let raw = obj.metadata.as_ref()?.description.clone()?;
    let flat = raw.split_whitespace().collect::<Vec<_>>().join(" ");
    (!flat.is_empty()).then(|| flat.replace('|', "\\|"))
}

/// A short human type label for a field schema: a referenced type name, a
/// primitive, `array of X`, `object of X`, or `X or null` for a nullable field.
fn type_label(schema: &Schema) -> String {
    match schema {
        Schema::Bool(_) => "any".to_string(),
        Schema::Object(o) => type_label_obj(o),
    }
}

fn type_label_obj(o: &SchemaObject) -> String {
    if let Some(r) = &o.reference {
        return ref_name(r);
    }
    // Option<T> / unions surface as anyOf/oneOf.
    if let Some(sub) = &o.subschemas {
        for group in [&sub.any_of, &sub.one_of, &sub.all_of]
            .into_iter()
            .flatten()
        {
            let parts: Vec<String> = group.iter().map(type_label).collect();
            if !parts.is_empty() {
                return parts.join(" or ");
            }
        }
    }
    if let Some(it) = &o.instance_type {
        return match it {
            SingleOrVec::Single(t) => label_for_instance(t, o),
            SingleOrVec::Vec(ts) => ts
                .iter()
                .map(|t| label_for_instance(t, o))
                .collect::<Vec<_>>()
                .join(" or "),
        };
    }
    // A bare map with only additionalProperties (no declared instance type).
    if let Some(ov) = &o.object {
        if let Some(ap) = &ov.additional_properties {
            return format!("object of {}", type_label(ap));
        }
    }
    "object".to_string()
}

/// Label a single instance type, expanding `array`/`object` into their element
/// / value shape when the schema declares one.
fn label_for_instance(t: &InstanceType, o: &SchemaObject) -> String {
    match t {
        InstanceType::Null => "null".to_string(),
        InstanceType::Boolean => "boolean".to_string(),
        InstanceType::Number => "number".to_string(),
        InstanceType::Integer => "integer".to_string(),
        InstanceType::String => "string".to_string(),
        InstanceType::Array => match o.array.as_ref().and_then(|a| a.items.as_ref()) {
            Some(SingleOrVec::Single(item)) => format!("array of {}", type_label(item)),
            Some(SingleOrVec::Vec(items)) => items
                .first()
                .map(|i| format!("array of {}", type_label(i)))
                .unwrap_or_else(|| "array".to_string()),
            None => "array".to_string(),
        },
        InstanceType::Object => match o
            .object
            .as_ref()
            .and_then(|ov| ov.additional_properties.as_ref())
        {
            Some(ap) => format!("object of {}", type_label(ap)),
            None => "object".to_string(),
        },
    }
}

/// `schema_with` target for an `Option<T>` field serde always writes (no
/// `skip_serializing_if`): the key is present, possibly `null`. Routing through
/// `schema_with` makes schemars list it as required while keeping `null` in the
/// type, which `#[schemars(required)]` would strip.
pub fn nullable<T: schemars::JsonSchema>(g: &mut schemars::gen::SchemaGenerator) -> Schema {
    g.subschema_for::<Option<T>>()
}

/// `#/definitions/DoctorReport` -> `DoctorReport`.
fn ref_name(r: &str) -> String {
    r.rsplit('/').next().unwrap_or(r).to_string()
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::{Path, PathBuf};

    /// Repo root, from this crate's manifest dir (`crates/rstest-cli`).
    fn repo_root() -> PathBuf {
        PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("../..")
            .canonicalize()
            .expect("repo root resolves")
    }

    /// Compare (or, with `bless`, write) `files` under `root`, and flag any file
    /// in `root/OUT_DIR` no output produces: leftovers from a renamed/removed
    /// output would otherwise keep being published. Returns the stale/orphaned
    /// repo-relative paths (always empty after a bless). Line endings are
    /// normalized so a CRLF checkout (Windows `core.autocrlf`) still matches.
    fn sync(root: &Path, files: &[GeneratedFile], bless: bool) -> Vec<String> {
        let mut stale = Vec::new();
        for f in files {
            let path = root.join(&f.rel_path);
            if bless {
                std::fs::create_dir_all(path.parent().unwrap()).unwrap();
                std::fs::write(&path, &f.contents).unwrap();
                continue;
            }
            let current = std::fs::read_to_string(&path).unwrap_or_default();
            if current.replace("\r\n", "\n") != f.contents {
                stale.push(f.rel_path.clone());
            }
        }
        let Ok(entries) = std::fs::read_dir(root.join(OUT_DIR)) else {
            return stale;
        };
        for entry in entries {
            let entry = entry.unwrap();
            let name = entry.file_name().to_string_lossy().into_owned();
            // Only files shaped like our artifacts can be orphans; leave
            // dotfiles (`.DS_Store`), editor/merge leftovers and dirs alone.
            let artifact_like = name.ends_with(".schema.json") || name.ends_with(".md");
            if name.starts_with('.') || !artifact_like || !entry.file_type().unwrap().is_file() {
                continue;
            }
            let rel = format!("{OUT_DIR}/{name}");
            if files.iter().any(|f| f.rel_path == rel) {
                continue;
            }
            if bless {
                std::fs::remove_file(root.join(&rel)).unwrap();
            } else {
                stale.push(rel);
            }
        }
        stale
    }

    /// The committed schema artifacts must equal what the current Rust types
    /// generate. Regenerate (bless) with:
    ///   `RSTEST_BLESS_SCHEMAS=1 cargo test -p rstest-cli schema`
    #[test]
    fn generated_schemas_match_committed() {
        let bless = std::env::var_os("RSTEST_BLESS_SCHEMAS").is_some();
        let stale = sync(&repo_root(), &generated_files(), bless);
        assert!(
            stale.is_empty(),
            "schema docs are stale or orphaned: {stale:?}\n\
             regenerate with: RSTEST_BLESS_SCHEMAS=1 cargo test -p rstest-cli schema"
        );
    }

    #[test]
    fn sync_reports_missing_stale_and_orphaned_files_and_bless_fixes_them() {
        let root = std::env::temp_dir().join(format!("rstest-schema-sync-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&root);
        let file = |name: &str, contents: &str| GeneratedFile {
            rel_path: format!("{OUT_DIR}/{name}"),
            contents: contents.to_string(),
        };
        let files = [file("a.md", "a\nb\n"), file("a.schema.json", "{}\n")];
        let dir = root.join(OUT_DIR);

        // Nothing on disk yet (no OUT_DIR at all): every artifact is missing.
        assert_eq!(sync(&root, &files, false).len(), 2);

        // Bless writes them; a normal run is then clean.
        assert!(sync(&root, &files, true).is_empty());
        assert!(sync(&root, &files, false).is_empty());

        // A CRLF checkout of the same content still matches.
        std::fs::write(dir.join("a.md"), "a\r\nb\r\n").unwrap();
        assert!(sync(&root, &files, false).is_empty());

        // Drifted content is stale; an unexpected file is orphaned.
        std::fs::write(dir.join("a.schema.json"), "{\"x\":1}\n").unwrap();
        std::fs::write(dir.join("old.md"), "gone\n").unwrap();
        assert_eq!(
            sync(&root, &files, false),
            [
                format!("{OUT_DIR}/a.schema.json"),
                format!("{OUT_DIR}/old.md")
            ]
        );

        // Non-artifacts are neither orphans nor deleted by bless: dotfiles,
        // other extensions, and directories (even artifact-named ones).
        std::fs::write(dir.join(".DS_Store"), "").unwrap();
        std::fs::write(dir.join(".a.md.swp"), "").unwrap();
        std::fs::write(dir.join("a.md.orig"), "").unwrap();
        std::fs::create_dir_all(dir.join("examples.md")).unwrap();

        // Bless rewrites the stale file and deletes the orphan.
        assert!(sync(&root, &files, true).is_empty());
        assert!(!dir.join("old.md").exists());
        for keep in [".DS_Store", ".a.md.swp", "a.md.orig", "examples.md"] {
            assert!(dir.join(keep).exists(), "{keep} should survive bless");
        }
        assert!(sync(&root, &files, false).is_empty());

        let _ = std::fs::remove_dir_all(&root);
    }

    fn label(v: serde_json::Value) -> String {
        type_label(&serde_json::from_value(v).expect("valid schema"))
    }

    #[test]
    fn type_label_covers_every_schema_shape() {
        use serde_json::json;
        assert_eq!(type_label(&Schema::Bool(true)), "any");
        assert_eq!(label(json!({"$ref": "#/definitions/Foo"})), "Foo");
        assert_eq!(
            label(json!({"anyOf": [{"$ref": "#/definitions/Foo"}, {"type": "null"}]})),
            "Foo or null"
        );
        assert_eq!(
            label(json!({"oneOf": [{"type": "integer"}, {"type": "string"}]})),
            "integer or string"
        );
        // An empty union falls through to the declared instance type.
        assert_eq!(label(json!({"allOf": [], "type": "boolean"})), "boolean");
        assert_eq!(label(json!({"type": ["number", "null"]})), "number or null");
        assert_eq!(
            label(json!({"type": "array", "items": {"type": "string"}})),
            "array of string"
        );
        // Tuple-style items: labelled by the first element.
        assert_eq!(
            label(json!({"type": "array", "items": [{"type": "integer"}, {"type": "string"}]})),
            "array of integer"
        );
        assert_eq!(label(json!({"type": "array", "items": []})), "array");
        assert_eq!(label(json!({"type": "array"})), "array");
        assert_eq!(
            label(json!({"type": "object", "additionalProperties": {"type": "number"}})),
            "object of number"
        );
        assert_eq!(label(json!({"type": "object"})), "object");
        // No instance type: a bare map, or nothing at all.
        assert_eq!(
            label(json!({"additionalProperties": {"type": "boolean"}})),
            "object of boolean"
        );
        assert_eq!(label(json!({"properties": {"x": {}}})), "object");
        assert_eq!(label(json!({})), "object");
    }

    fn with_description(desc: &str) -> SchemaObject {
        SchemaObject {
            metadata: Some(Box::new(schemars::schema::Metadata {
                description: Some(desc.to_string()),
                ..Default::default()
            })),
            ..Default::default()
        }
    }

    #[test]
    fn description_folds_whitespace_escapes_pipes_and_drops_blank() {
        assert_eq!(
            description(&with_description("a\n   b | c")).as_deref(),
            Some("a b \\| c")
        );
        assert_eq!(description(&with_description(" \n ")), None);
        assert_eq!(description(&SchemaObject::default()), None);
    }

    #[test]
    fn render_object_handles_non_object_empty_map_and_bool_fields() {
        use schemars::schema::ObjectValidation;

        // No object validation: heading, source and description only.
        let mut s = String::new();
        render_object(
            &mut s,
            "##",
            "Scalar",
            "`src`",
            &with_description("A value."),
        );
        assert_eq!(s, "## Scalar\n\nSource: `src`\n\nA value.\n\n\n");

        // An object with neither properties nor a value shape renders no table.
        let mut s = String::new();
        let empty = SchemaObject {
            object: Some(Box::default()),
            ..Default::default()
        };
        render_object(&mut s, "###", "Empty", "", &empty);
        assert_eq!(s, "### Empty\n\n");

        // A `true` (any) property: typed `any`, no description.
        let mut ov = ObjectValidation::default();
        ov.properties.insert("anything".into(), Schema::Bool(true));
        ov.required.insert("anything".into());
        let obj = SchemaObject {
            object: Some(Box::new(ov)),
            ..Default::default()
        };
        let mut s = String::new();
        render_object(&mut s, "###", "Loose", "", &obj);
        assert!(s.contains("| `anything` | any | yes |  |"), "{s}");
    }

    #[test]
    fn every_output_produces_two_artifacts() {
        // One .schema.json + one .md per output; names are unique.
        let files = generated_files();
        assert_eq!(files.len(), outputs().len() * 2);
        let json = files
            .iter()
            .filter(|f| f.rel_path.ends_with(".schema.json"))
            .count();
        assert_eq!(json, outputs().len());
    }
}
