//! Autogenerated JSON Schemas for the CLI's stable JSON outputs, plus a
//! markdown field-table rendering of each. The generated files are committed
//! under `docs/reference/schemas/` and embedded into the docs via pymdownx
//! snippets (`--8<--`), so the published reference is always exactly the Rust
//! types. A golden test ([`tests::generated_schemas_match_committed`]) fails if
//! a type drifts from its committed schema; regenerate with
//! `RSTEST_BLESS_SCHEMAS=1 cargo test -p rstest-cli schema`.
//!
//! Test-only: schemas are a documentation artifact, never emitted at runtime.
//! Adding an output is one entry in [`outputs`]; the `JsonSchema` derive on the
//! type does the rest.

use std::collections::HashMap;

use schemars::schema::{InstanceType, RootSchema, Schema, SchemaObject, SingleOrVec};
use schemars::schema_for;

/// Directory (repo-relative) the committed schema artifacts live in.
const OUT_DIR: &str = "docs/reference/schemas";

/// One documented JSON output: a stable `name` (the artifact filename stem), a
/// human `title`, the `source` that emits it, and its JSON Schema.
struct Output {
    name: &'static str,
    title: &'static str,
    source: &'static str,
    schema: RootSchema,
}

/// The outputs whose schema is published. Every stable JSON surface the CLI
/// emits is a typed serde struct; adding one here is all it takes.
fn outputs() -> Vec<Output> {
    vec![
        Output {
            name: "report-json",
            title: "Run report",
            source: "`--report-json`",
            schema: schema_for!(crate::reporting::report::Snapshot<'static>),
        },
        Output {
            name: "doctor-report",
            title: "Doctor report",
            source: "`--doctor-json`",
            schema: schema_for!(crate::doctor::DoctorReport),
        },
        Output {
            name: "discovery",
            title: "Discovery",
            source: "`--collect-only --report-json`",
            schema: schema_for!(crate::run::discovery::DiscoveryDoc),
        },
        Output {
            name: "migrate-check",
            title: "Migrate-check",
            source: "`migrate-check --migrate-check-json`",
            schema: schema_for!(crate::migrate::check::MigrateCheckDoc),
        },
        Output {
            name: "flake-log",
            title: "Flake log",
            source: "`.rstest_cache/flakes.json`",
            schema: schema_for!(HashMap<String, crate::reporting::flakes::FlakeStats>),
        },
    ]
}

/// A generated file: repo-relative path + full contents (trailing newline).
pub struct GeneratedFile {
    pub rel_path: String,
    pub contents: String,
}

/// Every artifact that should exist on disk: one `.schema.json` and one `.md`
/// field-table per output.
pub fn generated_files() -> Vec<GeneratedFile> {
    let mut files = Vec::new();
    for o in outputs() {
        let mut json = serde_json::to_string_pretty(&o.schema).expect("schema serializes");
        json.push('\n');
        files.push(GeneratedFile {
            rel_path: format!("{OUT_DIR}/{}.schema.json", o.name),
            contents: json,
        });
        files.push(GeneratedFile {
            rel_path: format!("{OUT_DIR}/{}.md", o.name),
            contents: render_md(&o),
        });
    }
    files
}

/// The generated markdown for one output: the root object, then a table per
/// referenced sub-type (definitions), in a stable (alphabetical) order.
fn render_md(o: &Output) -> String {
    let mut s = String::new();
    s.push_str(
        "<!-- Generated from the Rust type by `cargo test -p rstest-cli schema`. \
         Do not edit by hand; regenerate with RSTEST_BLESS_SCHEMAS=1. -->\n\n",
    );
    // Root type at `##`, its referenced sub-types at `###`, for clean toc nesting.
    render_object(&mut s, "##", o.title, o.source, &o.schema.schema);
    for (name, sch) in &o.schema.definitions {
        if let Schema::Object(obj) = sch {
            render_object(&mut s, "###", name, "", obj);
        }
    }
    s
}

/// Render one object schema as a `heading` (markdown level marker) + optional
/// description + a property table. Also handles a map root (no properties, just
/// `additionalProperties`), which is how `flakes.json` is shaped.
fn render_object(s: &mut String, level: &str, heading: &str, source: &str, obj: &SchemaObject) {
    use std::fmt::Write;

    let _ = write!(s, "{level} {heading}\n\n");
    if !source.is_empty() {
        let _ = write!(s, "Source: {source}\n\n");
    }
    if let Some(desc) = description(obj) {
        let _ = write!(s, "{desc}\n\n");
    }

    let Some(ov) = &obj.object else {
        s.push('\n');
        return;
    };

    // A map type (e.g. nodeid -> record): no fixed properties, one value shape.
    if ov.properties.is_empty() {
        if let Some(ap) = &ov.additional_properties {
            let _ = write!(
                s,
                "An object mapping each key to a {} value.\n\n",
                type_label(ap)
            );
        }
        return;
    }

    s.push_str("| Field | Type | Required | Description |\n|---|---|---|---|\n");
    // `properties` is a BTreeMap, so iteration is already alphabetical & stable.
    for (field, sch) in &ov.properties {
        let required = if ov.required.contains(field) {
            "yes"
        } else {
            "no"
        };
        let ty = type_label(sch);
        let desc = match sch {
            Schema::Object(o) => description(o).unwrap_or_default(),
            Schema::Bool(_) => String::new(),
        };
        let _ = writeln!(s, "| `{field}` | {ty} | {required} | {desc} |");
    }
    s.push('\n');
}

/// A cell-safe one-line description from a schema's metadata (newlines folded,
/// `|` escaped so it can't break the table).
fn description(obj: &SchemaObject) -> Option<String> {
    let raw = obj.metadata.as_ref()?.description.clone()?;
    let flat = raw.split_whitespace().collect::<Vec<_>>().join(" ");
    (!flat.is_empty()).then(|| flat.replace('|', "\\|"))
}

/// A short human type label for a field schema: a referenced type name, a
/// primitive, `array of X`, `object of X`, or `X or null` for a nullable field.
fn type_label(schema: &Schema) -> String {
    match schema {
        Schema::Bool(_) => "any".to_string(),
        Schema::Object(o) => type_label_obj(o),
    }
}

fn type_label_obj(o: &SchemaObject) -> String {
    if let Some(r) = &o.reference {
        return ref_name(r);
    }
    // Option<T> / unions surface as anyOf/oneOf.
    if let Some(sub) = &o.subschemas {
        for group in [&sub.any_of, &sub.one_of, &sub.all_of]
            .into_iter()
            .flatten()
        {
            let parts: Vec<String> = group.iter().map(type_label).collect();
            if !parts.is_empty() {
                return parts.join(" or ");
            }
        }
    }
    if let Some(it) = &o.instance_type {
        return match it {
            SingleOrVec::Single(t) => label_for_instance(t, o),
            SingleOrVec::Vec(ts) => ts
                .iter()
                .map(|t| label_for_instance(t, o))
                .collect::<Vec<_>>()
                .join(" or "),
        };
    }
    // A bare map with only additionalProperties (no declared instance type).
    if let Some(ov) = &o.object {
        if let Some(ap) = &ov.additional_properties {
            return format!("object of {}", type_label(ap));
        }
    }
    "object".to_string()
}

/// Label a single instance type, expanding `array`/`object` into their element
/// / value shape when the schema declares one.
fn label_for_instance(t: &InstanceType, o: &SchemaObject) -> String {
    match t {
        InstanceType::Null => "null".to_string(),
        InstanceType::Boolean => "boolean".to_string(),
        InstanceType::Number => "number".to_string(),
        InstanceType::Integer => "integer".to_string(),
        InstanceType::String => "string".to_string(),
        InstanceType::Array => match o.array.as_ref().and_then(|a| a.items.as_ref()) {
            Some(SingleOrVec::Single(item)) => format!("array of {}", type_label(item)),
            Some(SingleOrVec::Vec(items)) => items
                .first()
                .map(|i| format!("array of {}", type_label(i)))
                .unwrap_or_else(|| "array".to_string()),
            None => "array".to_string(),
        },
        InstanceType::Object => match o
            .object
            .as_ref()
            .and_then(|ov| ov.additional_properties.as_ref())
        {
            Some(ap) => format!("object of {}", type_label(ap)),
            None => "object".to_string(),
        },
    }
}

/// `#/definitions/DoctorReport` -> `DoctorReport`.
fn ref_name(r: &str) -> String {
    r.rsplit('/').next().unwrap_or(r).to_string()
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    /// Repo root, from this crate's manifest dir (`crates/rstest-cli`).
    fn repo_root() -> PathBuf {
        PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("../..")
            .canonicalize()
            .expect("repo root resolves")
    }

    /// The committed schema artifacts must equal what the current Rust types
    /// generate. Regenerate (bless) with:
    ///   `RSTEST_BLESS_SCHEMAS=1 cargo test -p rstest-cli schema`
    #[test]
    fn generated_schemas_match_committed() {
        let root = repo_root();
        let bless = std::env::var_os("RSTEST_BLESS_SCHEMAS").is_some();
        let mut stale = Vec::new();
        for f in generated_files() {
            let path = root.join(&f.rel_path);
            if bless {
                std::fs::create_dir_all(path.parent().unwrap()).unwrap();
                std::fs::write(&path, &f.contents).unwrap();
                continue;
            }
            let current = std::fs::read_to_string(&path).unwrap_or_default();
            if current != f.contents {
                stale.push(f.rel_path);
            }
        }
        assert!(
            bless || stale.is_empty(),
            "schema docs are stale: {stale:?}\n\
             regenerate with: RSTEST_BLESS_SCHEMAS=1 cargo test -p rstest-cli schema"
        );
    }

    #[test]
    fn every_output_produces_two_artifacts() {
        // One .schema.json + one .md per output; names are unique.
        let files = generated_files();
        assert_eq!(files.len(), outputs().len() * 2);
        let json = files
            .iter()
            .filter(|f| f.rel_path.ends_with(".schema.json"))
            .count();
        assert_eq!(json, outputs().len());
    }
}
