//! Autogenerated JSON Schemas for the CLI's stable JSON outputs, plus a
//! markdown field-table rendering of each. The generated files are committed
//! under `docs/reference/schemas/` and embedded into the docs via pymdownx
//! snippets (`--8<--`), so the published reference is always exactly the Rust
//! types. A golden test ([`tests::generated_schemas_match_committed`]) fails if
//! a type drifts from its committed schema; regenerate with
//! `RSTEST_BLESS_SCHEMAS=1 cargo test -p rstest-cli schema`.
//!
//! Test-only: schemas are a documentation artifact, never emitted at runtime.
//! Adding an output is one entry in [`outputs`]; the `JsonSchema` derive on the
//! type does the rest.

use std::collections::HashMap;

use schemars::generate::SchemaSettings;
use schemars::{JsonSchema, Schema};
use serde_json::{Map, Value};

/// Directory (repo-relative) the committed schema artifacts live in.
const OUT_DIR: &str = "docs/reference/schemas";

/// One documented JSON output: a stable `name` (the artifact filename stem), a
/// human `title`, the `source` that emits it, and its JSON Schema.
struct Output {
    name: &'static str,
    title: &'static str,
    source: &'static str,
    schema: Schema,
}

/// Root schema for `T`. Pinned to draft-07 (schemars 1 defaults to 2020-12) so
/// the published dialect and `#/definitions/...` refs stay stable for consumers.
fn schema_of<T: JsonSchema>() -> Schema {
    SchemaSettings::draft07()
        .into_generator()
        .into_root_schema_for::<T>()
}

/// The outputs whose schema is published. Every stable JSON surface the CLI
/// emits is a typed serde struct; adding one here is all it takes.
fn outputs() -> Vec<Output> {
    vec![
        Output {
            name: "report-json",
            title: "Run report",
            source: "`--report-json`",
            schema: schema_of::<crate::reporting::report::Snapshot<'static>>(),
        },
        Output {
            name: "doctor-report",
            title: "Doctor report",
            source: "`--doctor-json`",
            schema: schema_of::<crate::doctor::DoctorReport>(),
        },
        Output {
            name: "discovery",
            title: "Discovery",
            source: "`--collect-only --report-json`",
            schema: schema_of::<crate::run::discovery::DiscoveryDoc>(),
        },
        Output {
            name: "migrate-check",
            title: "Migrate-check",
            source: "`migrate-check --migrate-check-json`",
            schema: schema_of::<crate::migrate::check::MigrateCheckDoc>(),
        },
        Output {
            name: "audit",
            title: "Audit",
            source: "`audit --audit-json`",
            schema: schema_of::<crate::migrate::audit::AuditDoc>(),
        },
        Output {
            name: "bisect",
            title: "Bisect",
            source: "`bisect --bisect-json`",
            schema: schema_of::<crate::migrate::bisect::BisectDoc>(),
        },
        Output {
            name: "explain",
            title: "Explain",
            source: "`explain --json`",
            schema: schema_of::<crate::explain::ExplainReport>(),
        },
        Output {
            name: "flake-log",
            title: "Flake log",
            source: "`.rstest_cache/flakes.json`",
            schema: schema_of::<HashMap<String, crate::reporting::flakes::FlakeStats>>(),
        },
    ]
}

/// A generated file: repo-relative path + full contents (trailing newline).
pub struct GeneratedFile {
    pub rel_path: String,
    pub contents: String,
}

/// Every artifact that should exist on disk: one `.schema.json` and one `.md`
/// field-table per output.
pub fn generated_files() -> Vec<GeneratedFile> {
    let mut files = Vec::new();
    for o in outputs() {
        let mut json = serde_json::to_string_pretty(&o.schema).expect("schema serializes");
        json.push('\n');
        files.push(GeneratedFile {
            rel_path: format!("{OUT_DIR}/{}.schema.json", o.name),
            contents: json,
        });
        files.push(GeneratedFile {
            rel_path: format!("{OUT_DIR}/{}.md", o.name),
            contents: render_md(&o),
        });
    }
    files
}

/// `obj`'s entries sorted by key, so output order never depends on whether
/// serde_json's `preserve_order` feature is on somewhere in the build.
fn sorted(obj: &Map<String, Value>) -> Vec<(&String, &Value)> {
    let mut entries: Vec<_> = obj.iter().collect();
    entries.sort_by(|a, b| a.0.cmp(b.0));
    entries
}

/// The generated markdown for one output: the root object, then a table per
/// referenced sub-type (definitions), in a stable (alphabetical) order.
fn render_md(o: &Output) -> String {
    let mut s = String::new();
    s.push_str(
        "<!-- Generated from the Rust type by `cargo test -p rstest-cli schema`. \
         Do not edit by hand; regenerate with RSTEST_BLESS_SCHEMAS=1. -->\n\n",
    );
    // Root type at `##`, its referenced sub-types at `###`, for clean toc nesting.
    let empty = Map::new();
    let root = o.schema.as_object().unwrap_or(&empty);
    render_object(&mut s, "##", o.title, o.source, root);
    if let Some(Value::Object(defs)) = root.get("definitions") {
        for (name, sch) in sorted(defs) {
            if let Value::Object(obj) = sch {
                render_object(&mut s, "###", name, "", obj);
            }
        }
    }
    // Exactly one trailing newline, matching pre-commit's end-of-file-fixer.
    let trimmed = s.trim_end().len();
    s.truncate(trimmed);
    s.push('\n');
    s
}

/// Render one object schema as a `heading` (markdown level marker) + optional
/// description + a property table. Also handles a map root (no properties, just
/// `additionalProperties`), which is how `flakes.json` is shaped.
fn render_object(
    s: &mut String,
    level: &str,
    heading: &str,
    source: &str,
    obj: &Map<String, Value>,
) {
    use std::fmt::Write;

    let _ = write!(s, "{level} {heading}\n\n");
    if !source.is_empty() {
        let _ = write!(s, "Source: {source}\n\n");
    }
    if let Some(desc) = description(obj) {
        let _ = write!(s, "{desc}\n\n");
    }

    let props = match obj.get("properties") {
        Some(Value::Object(p)) => Some(p),
        _ => None,
    };
    let ap = obj.get("additionalProperties");
    if props.is_none() && ap.is_none() {
        s.push('\n');
        return;
    }

    // A map type (e.g. nodeid -> record): no fixed properties, one value shape.
    let Some(props) = props.filter(|p| !p.is_empty()) else {
        if let Some(ap) = ap {
            let _ = write!(
                s,
                "An object mapping each key to a {} value.\n\n",
                type_label(ap)
            );
        }
        return;
    };

    let required: Vec<&str> = obj
        .get("required")
        .and_then(Value::as_array)
        .map(|r| r.iter().filter_map(Value::as_str).collect())
        .unwrap_or_default();
    s.push_str("| Field | Type | Required | Description |\n|---|---|---|---|\n");
    for (field, sch) in sorted(props) {
        let required = if required.contains(&field.as_str()) {
            "yes"
        } else {
            "no"
        };
        let ty = type_label(sch);
        let desc = sch.as_object().and_then(description).unwrap_or_default();
        let _ = writeln!(s, "| `{field}` | {ty} | {required} | {desc} |");
    }
    s.push('\n');
}

/// A cell-safe one-line description from a schema's metadata (newlines folded,
/// `|` escaped so it can't break the table).
fn description(obj: &Map<String, Value>) -> Option<String> {
    let raw = obj.get("description")?.as_str()?;
    let flat = raw.split_whitespace().collect::<Vec<_>>().join(" ");
    (!flat.is_empty()).then(|| flat.replace('|', "\\|"))
}

/// A short human type label for a field schema: a referenced type name, a
/// primitive, `array of X`, `object of X`, or `X or null` for a nullable field.
fn type_label(schema: &Value) -> String {
    let Value::Object(o) = schema else {
        // `true`/`false` schemas (and anything malformed) accept any value.
        return "any".to_string();
    };
    if let Some(r) = o.get("$ref").and_then(Value::as_str) {
        return ref_name(r);
    }
    // Option<T> / unions surface as anyOf/oneOf.
    for key in ["anyOf", "oneOf", "allOf"] {
        if let Some(Value::Array(group)) = o.get(key) {
            if !group.is_empty() {
                return group
                    .iter()
                    .map(type_label)
                    .collect::<Vec<_>>()
                    .join(" or ");
            }
        }
    }
    match o.get("type") {
        Some(Value::String(t)) => return label_for_instance(t, o),
        Some(Value::Array(ts)) => {
            return ts
                .iter()
                .filter_map(Value::as_str)
                .map(|t| label_for_instance(t, o))
                .collect::<Vec<_>>()
                .join(" or ");
        }
        _ => {}
    }
    // A bare map with only additionalProperties (no declared instance type).
    if let Some(ap) = o.get("additionalProperties") {
        return format!("object of {}", type_label(ap));
    }
    "object".to_string()
}

/// Label a single instance type, expanding `array`/`object` into their element
/// / value shape when the schema declares one.
fn label_for_instance(t: &str, o: &Map<String, Value>) -> String {
    match t {
        "array" => match o.get("items") {
            Some(Value::Array(items)) => items
                .first()
                .map(|i| format!("array of {}", type_label(i)))
                .unwrap_or_else(|| "array".to_string()),
            Some(item) => format!("array of {}", type_label(item)),
            None => "array".to_string(),
        },
        "object" => match o.get("additionalProperties") {
            Some(ap) => format!("object of {}", type_label(ap)),
            None => "object".to_string(),
        },
        other => other.to_string(),
    }
}

/// `schema_with` target for an `Option<T>` field serde always writes (no
/// `skip_serializing_if`): the key is present, possibly `null`. Routing through
/// `schema_with` makes schemars list it as required while keeping `null` in the
/// type, which `#[schemars(required)]` would strip.
pub fn nullable<T: JsonSchema>(g: &mut schemars::SchemaGenerator) -> Schema {
    g.subschema_for::<Option<T>>()
}

/// `#/definitions/DoctorReport` -> `DoctorReport`.
fn ref_name(r: &str) -> String {
    r.rsplit('/').next().unwrap_or(r).to_string()
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::{Path, PathBuf};

    /// Repo root, from this crate's manifest dir (`crates/rstest-cli`).
    fn repo_root() -> PathBuf {
        PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("../..")
            .canonicalize()
            .expect("repo root resolves")
    }

    /// Compare (or, with `bless`, write) `files` under `root`, and flag any file
    /// in `root/OUT_DIR` no output produces: leftovers from a renamed/removed
    /// output would otherwise keep being published. Returns the stale/orphaned
    /// repo-relative paths (always empty after a bless). Line endings are
    /// normalized so a CRLF checkout (Windows `core.autocrlf`) still matches.
    fn sync(root: &Path, files: &[GeneratedFile], bless: bool) -> Vec<String> {
        let mut stale = Vec::new();
        for f in files {
            let path = root.join(&f.rel_path);
            if bless {
                std::fs::create_dir_all(path.parent().unwrap()).unwrap();
                std::fs::write(&path, &f.contents).unwrap();
                continue;
            }
            let current = std::fs::read_to_string(&path).unwrap_or_default();
            if current.replace("\r\n", "\n") != f.contents {
                stale.push(f.rel_path.clone());
            }
        }
        let Ok(entries) = std::fs::read_dir(root.join(OUT_DIR)) else {
            return stale;
        };
        for entry in entries {
            let entry = entry.unwrap();
            let name = entry.file_name().to_string_lossy().into_owned();
            // Only files shaped like our artifacts can be orphans; leave
            // dotfiles (`.DS_Store`), editor/merge leftovers and dirs alone.
            let artifact_like = name.ends_with(".schema.json") || name.ends_with(".md");
            if name.starts_with('.') || !artifact_like || !entry.file_type().unwrap().is_file() {
                continue;
            }
            let rel = format!("{OUT_DIR}/{name}");
            if files.iter().any(|f| f.rel_path == rel) {
                continue;
            }
            if bless {
                std::fs::remove_file(root.join(&rel)).unwrap();
            } else {
                stale.push(rel);
            }
        }
        stale
    }

    /// The committed schema artifacts must equal what the current Rust types
    /// generate. Regenerate (bless) with:
    ///   `RSTEST_BLESS_SCHEMAS=1 cargo test -p rstest-cli schema`
    #[test]
    fn generated_schemas_match_committed() {
        let bless = std::env::var_os("RSTEST_BLESS_SCHEMAS").is_some();
        let stale = sync(&repo_root(), &generated_files(), bless);
        assert!(
            stale.is_empty(),
            "schema docs are stale or orphaned: {stale:?}\n\
             regenerate with: RSTEST_BLESS_SCHEMAS=1 cargo test -p rstest-cli schema"
        );
    }

    #[test]
    fn sync_reports_missing_stale_and_orphaned_files_and_bless_fixes_them() {
        let root = std::env::temp_dir().join(format!("rstest-schema-sync-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&root);
        let file = |name: &str, contents: &str| GeneratedFile {
            rel_path: format!("{OUT_DIR}/{name}"),
            contents: contents.to_string(),
        };
        let files = [file("a.md", "a\nb\n"), file("a.schema.json", "{}\n")];
        let dir = root.join(OUT_DIR);

        // Nothing on disk yet (no OUT_DIR at all): every artifact is missing.
        assert_eq!(sync(&root, &files, false).len(), 2);

        // Bless writes them; a normal run is then clean.
        assert!(sync(&root, &files, true).is_empty());
        assert!(sync(&root, &files, false).is_empty());

        // A CRLF checkout of the same content still matches.
        std::fs::write(dir.join("a.md"), "a\r\nb\r\n").unwrap();
        assert!(sync(&root, &files, false).is_empty());

        // Drifted content is stale; an unexpected file is orphaned.
        std::fs::write(dir.join("a.schema.json"), "{\"x\":1}\n").unwrap();
        std::fs::write(dir.join("old.md"), "gone\n").unwrap();
        assert_eq!(
            sync(&root, &files, false),
            [
                format!("{OUT_DIR}/a.schema.json"),
                format!("{OUT_DIR}/old.md")
            ]
        );

        // Non-artifacts are neither orphans nor deleted by bless: dotfiles,
        // other extensions, and directories (even artifact-named ones).
        std::fs::write(dir.join(".DS_Store"), "").unwrap();
        std::fs::write(dir.join(".a.md.swp"), "").unwrap();
        std::fs::write(dir.join("a.md.orig"), "").unwrap();
        std::fs::create_dir_all(dir.join("examples.md")).unwrap();

        // Bless rewrites the stale file and deletes the orphan.
        assert!(sync(&root, &files, true).is_empty());
        assert!(!dir.join("old.md").exists());
        for keep in [".DS_Store", ".a.md.swp", "a.md.orig", "examples.md"] {
            assert!(dir.join(keep).exists(), "{keep} should survive bless");
        }
        assert!(sync(&root, &files, false).is_empty());

        let _ = std::fs::remove_dir_all(&root);
    }

    fn label(v: serde_json::Value) -> String {
        type_label(&v)
    }

    #[test]
    fn type_label_covers_every_schema_shape() {
        use serde_json::json;
        assert_eq!(label(json!(true)), "any");
        assert_eq!(label(json!({"$ref": "#/definitions/Foo"})), "Foo");
        assert_eq!(
            label(json!({"anyOf": [{"$ref": "#/definitions/Foo"}, {"type": "null"}]})),
            "Foo or null"
        );
        assert_eq!(
            label(json!({"oneOf": [{"type": "integer"}, {"type": "string"}]})),
            "integer or string"
        );
        // An empty union falls through to the declared instance type.
        assert_eq!(label(json!({"allOf": [], "type": "boolean"})), "boolean");
        assert_eq!(label(json!({"type": ["number", "null"]})), "number or null");
        assert_eq!(
            label(json!({"type": "array", "items": {"type": "string"}})),
            "array of string"
        );
        // Tuple-style items: labelled by the first element.
        assert_eq!(
            label(json!({"type": "array", "items": [{"type": "integer"}, {"type": "string"}]})),
            "array of integer"
        );
        assert_eq!(label(json!({"type": "array", "items": []})), "array");
        assert_eq!(label(json!({"type": "array"})), "array");
        assert_eq!(
            label(json!({"type": "object", "additionalProperties": {"type": "number"}})),
            "object of number"
        );
        assert_eq!(label(json!({"type": "object"})), "object");
        // No instance type: a bare map, or nothing at all.
        assert_eq!(
            label(json!({"additionalProperties": {"type": "boolean"}})),
            "object of boolean"
        );
        assert_eq!(label(json!({"properties": {"x": {}}})), "object");
        assert_eq!(label(json!({})), "object");
    }

    fn obj(v: serde_json::Value) -> Map<String, Value> {
        match v {
            Value::Object(m) => m,
            other => panic!("not an object: {other}"),
        }
    }

    #[test]
    fn description_folds_whitespace_escapes_pipes_and_drops_blank() {
        use serde_json::json;
        assert_eq!(
            description(&obj(json!({"description": "a\n   b | c"}))).as_deref(),
            Some("a b \\| c")
        );
        assert_eq!(description(&obj(json!({"description": " \n "}))), None);
        assert_eq!(description(&Map::new()), None);
    }

    #[test]
    fn render_object_handles_non_object_empty_map_and_bool_fields() {
        use serde_json::json;

        // No object keywords: heading, source and description only.
        let mut s = String::new();
        render_object(
            &mut s,
            "##",
            "Scalar",
            "`src`",
            &obj(json!({"description": "A value."})),
        );
        assert_eq!(s, "## Scalar\n\nSource: `src`\n\nA value.\n\n\n");

        // An object with neither properties nor a value shape renders no table.
        let mut s = String::new();
        render_object(&mut s, "###", "Empty", "", &obj(json!({"properties": {}})));
        assert_eq!(s, "### Empty\n\n");

        // A `true` (any) property: typed `any`, no description.
        let loose = obj(json!({"properties": {"anything": true}, "required": ["anything"]}));
        let mut s = String::new();
        render_object(&mut s, "###", "Loose", "", &loose);
        assert!(s.contains("| `anything` | any | yes |  |"), "{s}");
    }

    #[test]
    fn every_output_produces_two_artifacts() {
        // One .schema.json + one .md per output; names are unique.
        let files = generated_files();
        assert_eq!(files.len(), outputs().len() * 2);
        let json = files
            .iter()
            .filter(|f| f.rel_path.ends_with(".schema.json"))
            .count();
        assert_eq!(json, outputs().len());
    }
}
